### ISSUE TITLE
Docker start: "container already exists" error

### ISSUE THREAD

**Issue by AlexBoulyga** [docker/for-linux#211]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
docker start oracle-xe
- Should start the container

### Actual behavior
Error response from daemon: container "0bab935448d88f2e3323cfc94a91b48e661d2eec08ac5a7359e71bf59d813211": already exists
Error: failed to start containers: oracle-xe

### Steps to reproduce the behavior
I have a container from the wnameless/oracle-xe-11g image, created with

docker run --name oracle-xe -d -p 49162:22 -p 49163:1521 -v ~/workspace/mcc:/app -e ORACLE_ALLOW_REMOTE=true wnameless/oracle-xe-11g

This container was used for a long time (> 5 months) without errors until one day, it did not start

It seems similar to the error mentioned here:
https://github.com/moby/moby/issues/20570
as the ID seems to be the already existing part.

However the error should have been already fixed in docḱer 1.11.
I was not able to find anything else producing this or a similar error!
I hope somebody has an idea how this was caused and how this could be fixed (besides re-creating the container)

thanks

docker ps -a:
```
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                           PORTS               NAMES
0bab935448d8        wnameless/oracle-xe-11g   "/bin/sh -c '/usr/sb…"   12 months ago       Exited (255) About an hour ago                       oracle-xe
```

docker inspect oracle-xe: See attached file
[docker_inspect_oracle-xe.txt](https://github.com/docker/for-linux/files/1672669/docker_inspect_oracle-xe.txt)

**Output of `docker version`:**
```
Client:
 Version:	18.02.0-ce-rc1
 API version:	1.35
 Go version:	go1.9.3
 Git commit:	5e1d90a
 Built:	Thu Jan 25 00:37:32 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce-rc1
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.3
  Git commit:	5e1d90a
  Built:	Thu Jan 25 00:36:06 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 499
Server Version: 18.02.0-ce-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 378
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 19.06GiB
Name: alex-ThinkPad-T460s
ID: M36E:R6MS:PPBH:U373:Y5OA:2ALT:TSEP:DGSS:O3TR:VZBE:7LMR:BRG6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by timothy-r-koski** [comment]
I'm seeing the same error after updating today on one of my containers.

`docker ps -a`
```
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                           PORTS                                                                   
b719d65aba25        local/oracle-ee-112-instance-base   "/assets/start_servi…"   3 weeks ago         Created                                                                                                   
d59994e971d5        wnameless/oracle-xe-11g             "/bin/sh -c '/usr/sb…"   10 months ago       Exited (137) About an hour ago                                                                            
b6ca6eb25133        wnameless/oracle-xe-11g             "/bin/sh -c '/usr/sb…"   16 months ago       Exited (255) 4 hours ago         0.0.0.0:1521->1521/tcp, 0.0.0.0:49160->22/tcp, 0.0.0.0:49161->8080/tcp   
```

`docker version`
```
Client:
 Version:	18.02.0-ce-rc1
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	5e1d90a
 Built:	Thu Jan 25 00:33:50 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce-rc1
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.3
  Git commit:	5e1d90a
  Built:	Thu Jan 25 00:40:43 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```
`docker info`
```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 16
Server Version: 18.02.0-ce-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 19
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.75-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: RQGP:VF5D:75KS:5WPI:ZS2O:OBQA:H67Q:JNMD:3EGP:4JQZ:CHZ4:X7ZR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 41
 System Time: 2018-01-30T20:46:01.299599241Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3128
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by cpuguy83** [comment]
This is being investigated at moby/moby#36145

**Comment by stevelacerda7** [comment]
Same issue here, looks like many others are having the same problem.

**Comment by nolazybits** [comment]
Same problem here.
```
docker info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 62
Server Version: 18.02.0-ce-rc2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.75-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: O6ND:CFJA:MN6B:5AZA:G475:RV4C:5HDN:BM6P:KTO5:7QRM:LTMQ:FIV7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 46
 System Time: 2018-02-08T21:34:51.282369523Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

```
docker start -i def25d460382                                       
Error response from daemon: container "def25d4603829d7db6c6c30da64ac514b1882ccef03ad1d0d707a50a4c19d6ce": already exists
```

Thanks

**Comment by cpuguy83** [comment]
This is fixed by moby/moby#36249

**Comment by ikbenben** [comment]
I'm experiencing this same issue. I see that it is addressed in a fix for Moby (not sure what Moby is :) ) but what kind of time frame are we looking for a release. I'm using experimental 8.02.0-ce-mac53 (22617) and the issue has kind of a put a screech on all work that I need to do. 

I'm on experimental because of another reason I had a year ago. Not sure if I can switch to Stable yet. I forget the reason now :)

**Comment by cpuguy83** [comment]
Assuming it gets merged before 18.03 is cut, it'll be in 18.03 and 17.12.1

**Comment by cpuguy83** [comment]
Actually this bug does not exist in 17.12, however if you tried to downgrade to 17.12 you will have this problem still.
Contemplating if we should include a cleanup patch in 17.12 to deal with this case... but in the meantime you can manually delete the containers from containerd.

```
docker-containerd-ctr --address /run/docker/containerd/docker-containerd.sock --namespace moby c rm <containerd id> 
```

**Comment by cpuguy83** [comment]
Closing since this issue will be resolved in 18.03. 18.02 is the only affected version as far as I can tell.
Sorry we didn't track this down in time for the 18.02 GA 😢 .

**Comment by Benjamin511** [comment]
Same error, when 18.03 is out ?

**Comment by cpuguy83** [comment]
March

**Comment by rkkoszewski** [comment]
Same issue here. After updating docker trough apt, Docker broke once again. The error I get is the same from post 1. 

Debian Stretch - Docker: 
Server:
 Engine:
  Version:      18.02.0-ce
  API version:  1.36 (minimum version 1.12)
  Go version:   go1.9.3
  Git commit:   fc4de44
  Built:        Wed Feb  7 21:14:59 2018
  OS/Arch:      linux/amd64
  Experimental: false

P.D: What is the best practice regarding updating Docker on a production server? It seems to periodically break ever now and then after an update.

**Comment by cpuguy83** [comment]
@rkkoszewski This is a bug with 18.02 specifically.
You may want to stick with the stable channel instead of edge... not that it's always bug free (especially 17.12).

**Comment by tao1** [comment]
Same issue here. I am relying on edge version because of Ubuntu 17.10.
I didn't see workaround in comments. Any clue ?

**Comment by eftakhairul** [comment]
I am getting the same error in OSX

**Comment by cpuguy83** [comment]
@tao1 https://github.com/docker/for-linux/issues/211#issuecomment-364947294
@eftakhairul Same as above, but you'll need to run that in a container and mount in the containerd socket.

**Comment by Benjamin511** [comment]
Any solution because i need start my containers and i can't recreate all in maximum 2 days ....

**Comment by boonkerz** [comment]
same issue on ubuntu  16.04

**Comment by cpuguy83** [comment]
Read the thread, people...

**Comment by mcoria** [comment]
Same issue...

$ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.02.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9b55aab90508bd389d7654c4baf173a981477d55
runc version: 9f9c96235cc97674e935002fc3d78361b696a69e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-5-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.5MiB
Name: debian-server
ID: EBHY:DMJC:H4AU:NFJN:DLH7:MTEG:47BZ:UPF7:IGNO:ZXM2:GCWU:S6PO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: coriamauricio
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by manast** [comment]
Note to self: ignore the auto-update advice and never upgrade docker unless strictly necessary... amazing how many times docker just breaks after upgrading...

**Comment by cpuguy83** [comment]
@manast I've not really experienced many issues like this on upgrade, but the edge channel is definitely more prone to it.

**Comment by rikless** [comment]
Is there any workaround ?

**Comment by cpuguy83** [comment]
@rikless https://github.com/docker/for-linux/issues/211#issuecomment-364947294

I'm going to lock this issue because it's just comments of "is there a work-around".
Yes, there is a work around, see the above mentioned comment.

**Comment by cpuguy83** [comment]
Thanks everyone! 🙇
